name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version:
          - 16

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        # potential optimization
        # uses: bahmutov/npm-install@v1
        run: npm i

      - name: Test
        run: npm t

      # - name: Install Coveralls
      #   run: npm install coveralls

      # - name: Coverage
      #   run: npm run coverage

      # - name: Coverage Report
      #   run: npm run coveralls
